const PRICES={CARTÃO:4.5,PEQUENO:13,MÉDIO:18,GRANDE:30};
const BOX_PREFIXES=['AMZC','AMZB','TXAQ'];
const SPECIAL_PAY_CITIES=new Set(['LIMOEIRO DO AJURU','SALVATERRA','SOURE']);
const STORAGE={payments:'w2_payments_v2',imports:'w2_imports_v2',extra:'w2_extra_data_v2'};
let base=(window.INITIAL_DATA||[]).map(enrichLegacy), extra=JSON.parse(localStorage.getItem(STORAGE.extra)||'[]').map(enrichLegacy);
let data=dedupe([...base,...extra]), charts={}, imports=JSON.parse(localStorage.getItem(STORAGE.imports)||'[]');
let payments=JSON.parse(localStorage.getItem(STORAGE.payments)||'[]'), activePaymentCity=null, pendingImport=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), num=v=>Number(v||0).toLocaleString('pt-BR');
const norm=s=>String(s??'').trim(), upper=s=>norm(s).toLocaleUpperCase('pt-BR');
function identifyType(awb){return BOX_PREFIXES.some(p=>upper(awb).startsWith(p))?'CAIXA':'CARTÃO'}
function classify(awb,peso){if(identifyType(awb)==='CARTÃO')return'CARTÃO';peso=Number(peso)||0;return peso<=1?'PEQUENO':peso<=10?'MÉDIO':'GRANDE'}
function deliveryRate(city){return SPECIAL_PAY_CITIES.has(upper(city))?8:5}
function parseDate(raw){if(!raw)return'';if(typeof raw==='number'&&window.XLSX){let x=XLSX.SSF.parse_date_code(raw);return x?`${x.y}-${String(x.m).padStart(2,'0')}-${String(x.d).padStart(2,'0')}`:''}if(raw instanceof Date&&!isNaN(raw))return raw.toISOString().slice(0,10);let s=String(raw);let m=s.match(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;let iso=s.match(/(\d{4})-(\d{2})-(\d{2})/);return iso?iso[0]:''}
function dateParts(s){let m=String(s||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?{year:+m[1],month:+m[2],quin:+m[3]<=15?1:2}:{} }
function enrichLegacy(r){let awb=norm(r.awb||r.awb1),peso=Number(r.peso||0),tipo=identifyType(awb),tamanho=classify(awb,peso);return{...r,caf:norm(r.caf||r.cafid1),awb,peso,tipo_item:tipo,tamanho,valor_unitario:PRICES[tamanho],data:parseDate(r.data||r.dt_finalizada_caf),cidade:norm(r.cidade),uf:norm(r.uf)}}
function dedupe(rows){let seen=new Set();return rows.filter(r=>{let k=`${upper(r.caf)}|${upper(r.awb)}`;if(!r.caf||!r.awb||seen.has(k))return false;seen.add(k);return true})}
function selectedMonths(){return $$('#monthMenu input[type=checkbox]:checked').map(o=>o.value)}
function updateMonthLabel(){let m=selectedMonths(),names=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];$('#monthToggle').childNodes[0].nodeValue=!m.length?'Todos os meses ':m.length===1?names[Number(m[0])-1]+' ':m.length===12?'Todos os meses ':m.length+' meses selecionados '}
function renderMonthMenu(){let names=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];$('#monthMenu').innerHTML=`<div class="month-actions"><button type="button" id="monthAll">Selecionar todos</button><button type="button" id="monthNone">Limpar</button></div>`+names.map((x,i)=>`<label class="month-option"><input type="checkbox" value="${i+1}"> <span>${x}</span></label>`).join('');updateMonthLabel()}
function filtered(){let months=selectedMonths();return data.filter(r=>{let p=dateParts(r.data);return(!$('#fAno').value||p.year==$('#fAno').value)&&(!months.length||months.includes(String(p.month)))&&(!$('#fQuinzena').value||p.quin==$('#fQuinzena').value)&&(!$('#fCidade').value||r.cidade==$('#fCidade').value)&&(!$('#fTamanho').value||r.tamanho==$('#fTamanho').value)})}
function populateFilters(){let years=[...new Set(data.map(r=>dateParts(r.data).year).filter(Boolean))].sort(),cities=[...new Set(data.map(r=>r.cidade).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('#fAno').innerHTML='<option value="">Todos os anos</option>'+years.map(x=>`<option>${x}</option>`).join('');renderMonthMenu();$('#fCidade').innerHTML='<option value="">Todas as cidades</option>'+cities.map(x=>`<option>${x}</option>`).join('')}
function makeChart(id,type,labels,values,label){if(typeof window.Chart==='undefined')return;if(charts[id])charts[id].destroy();const c=$(id);if(!c)return;charts[id]=new Chart(c.getContext('2d'),{type,data:{labels,datasets:[{label,data:values,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,animation:{duration:200},plugins:{legend:{display:type==='doughnut'}},scales:type==='doughnut'?{}:{y:{beginAtZero:true,ticks:{callback:v=>label==='R$'?brl(v):num(v)}}}}})}
function table(headers,rows){return`<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function render(){let d=filtered();$('#kAwb').textContent=num(d.length);$('#kCaf').textContent=num(new Set(d.map(r=>r.caf)).size);$('#kCidade').textContent=num(new Set(d.map(r=>r.cidade)).size);$('#kPeso').textContent=num(d.reduce((s,r)=>s+r.peso,0).toFixed(2))+' kg';$('#kFat').textContent=brl(d.reduce((s,r)=>s+PRICES[r.tamanho],0));let cats=['CARTÃO','PEQUENO','MÉDIO','GRANDE'];makeChart('#chartCat','doughnut',cats,cats.map(c=>d.filter(r=>r.tamanho===c).length),'AWBs');let mm={};d.forEach(r=>{let p=dateParts(r.data),k=p.year+'-'+String(p.month).padStart(2,'0');mm[k]=(mm[k]||0)+PRICES[r.tamanho]});let ks=Object.keys(mm).sort();makeChart('#chartMes','bar',ks,ks.map(k=>mm[k]),'R$');let cm={};d.forEach(r=>cm[r.cidade]=(cm[r.cidade]||0)+1);let top=Object.entries(cm).sort((a,b)=>b[1]-a[1]).slice(0,10);makeChart('#chartCidade','bar',top.map(x=>x[0]),top.map(x=>x[1]),'AWBs');renderCities(d);renderBilling(d);renderPayments(d)}
function renderCities(d){let m={};d.forEach(r=>{let x=m[r.cidade]??={cafs:new Set(),awb:0,fat:0,pay:0};x.cafs.add(r.caf);x.awb++;x.fat+=PRICES[r.tamanho];x.pay+=deliveryRate(r.cidade)});let rows=Object.entries(m).sort((a,b)=>b[1].awb-a[1].awb).map(([c,x])=>`<tr><td>${c}</td><td>${x.cafs.size}</td><td>${num(x.awb)}</td><td>${brl(x.fat)}</td><td>${brl(x.pay)}</td></tr>`);$('#cityTable').innerHTML=table(['Cidade','CAFs','AWBs','Faturamento','Repasse'],rows)}
function renderBilling(d){let cats=['CARTÃO','PEQUENO','MÉDIO','GRANDE'];let rows=cats.map(c=>{let q=d.filter(r=>r.tamanho===c).length;return`<tr><td>${c}</td><td>${num(q)}</td><td>${brl(PRICES[c])}</td><td><b>${brl(q*PRICES[c])}</b></td></tr>`});$('#billingTable').innerHTML=table(['Categoria','Quantidade','Valor unitário','Total'],rows)}
function selectedPeriod(){return{year:$('#fAno').value,months:selectedMonths(),quin:$('#fQuinzena').value}}
function periodReady(){let p=selectedPeriod();return p.year&&p.months.length===1&&p.quin}
function periodLabel(){let p=selectedPeriod();return periodReady()?`${p.quin}ª quinzena ${String(p.months[0]).padStart(2,'0')}/${p.year}`:'período filtrado'}
function paymentMatches(p){let s=selectedPeriod();return(!s.year||p.year==s.year)&&(!s.months.length||s.months.includes(String(p.month)))&&(!s.quin||p.quin==s.quin)}
function paidFor(city){return payments.filter(p=>p.city===city&&paymentMatches(p)).reduce((s,p)=>s+Number(p.amount||0),0)}
function renderPayments(d=filtered()){let m={};d.forEach(r=>{let c=r.cidade||'NÃO INFORMADA',x=m[c]??={cafs:new Set(),awb:0,due:0};x.cafs.add(r.caf);x.awb++;x.due+=deliveryRate(c)});let due=Object.values(m).reduce((s,x)=>s+x.due,0),rev=d.reduce((s,r)=>s+PRICES[r.tamanho],0);$('#pAwb').textContent=num(d.length);$('#pCities').textContent=num(Object.keys(m).length);$('#pPay').textContent=brl(due);$('#pRevenue').textContent=brl(rev);$('#pMargin').textContent=brl(rev-due);let rows=Object.entries(m).sort((a,b)=>b[1].awb-a[1].awb).map(([c,x])=>{let paid=paidFor(c),debt=Math.max(0,x.due-paid),status=debt<=.005?'Pago':paid>0?'Parcial':'Pendente',cls=status.toLowerCase();return`<tr><td>${c}</td><td>${x.cafs.size}</td><td>${num(x.awb)}</td><td>${brl(deliveryRate(c))}</td><td>${brl(x.due)}</td><td class="paid">${brl(paid)}</td><td class="debt">${brl(debt)}</td><td><span class="status-pill status-${cls}">${status}</span></td><td><button class="pay-btn" data-city="${c}" ${periodReady()?'':'disabled'}>Registrar</button></td></tr>`});$('#paymentTable').innerHTML=(!periodReady()?'<div class="preview warn"><b>Para registrar pagamento, selecione um único mês, ano e quinzena.</b></div>':'')+table(['Cidade','CAFs','AWBs','Tarifa/AWB','Devido','Pago','Saldo','Status','Ação'],rows);renderPaymentHistory()}
function openPayment(city){if(!periodReady())return toast('Selecione um único mês, ano e quinzena.');let d=filtered().filter(r=>(r.cidade||'NÃO INFORMADA')===city),due=d.reduce((s,r)=>s+deliveryRate(city),0),paid=paidFor(city),debt=Math.max(0,due-paid);activePaymentCity=city;$('#paymentContext').textContent=`${city} • ${periodLabel()} • ${num(d.length)} AWBs • ${brl(deliveryRate(city))}/AWB`;$('#mDue').textContent=brl(due);$('#mPaid').textContent=brl(paid);$('#mDebt').textContent=brl(debt);$('#mAmount').value=debt.toFixed(2);$('#mDate').value=new Date().toISOString().slice(0,10);$('#mDriver').value=payments.find(x=>x.city===city)?.driver||'';$('#mNote').value='';$('#paymentModal').classList.add('open')}
function closePaymentModal(){$('#paymentModal').classList.remove('open');activePaymentCity=null}
function registerPayment(){if(!activePaymentCity)return;let amount=Number($('#mAmount').value),driver=$('#mDriver').value.trim(),date=$('#mDate').value;if(!driver||!date||!(amount>0))return toast('Preencha entregador, valor e data.');let d=filtered().filter(r=>r.cidade===activePaymentCity),due=d.reduce((s,r)=>s+deliveryRate(activePaymentCity),0),debt=Math.max(0,due-paidFor(activePaymentCity));if(amount>debt+.005)return toast('Valor maior que o saldo devedor.');let p=selectedPeriod();payments.unshift({id:Date.now(),city:activePaymentCity,driver,amount,date,note:$('#mNote').value.trim(),year:+p.year,month:+p.months[0],quin:+p.quin});localStorage.setItem(STORAGE.payments,JSON.stringify(payments));closePaymentModal();render();toast('Pagamento registrado.')}
function renderPaymentHistory(){let list=payments.filter(paymentMatches).sort((a,b)=>(b.date||'').localeCompare(a.date||''));$('#paymentHistory').innerHTML=list.length?table(['Data','Cidade','Entregador','Período','Valor','Observação',''],list.map(x=>`<tr><td>${x.date.split('-').reverse().join('/')}</td><td>${x.city}</td><td>${x.driver}</td><td>${x.quin}ª ${String(x.month).padStart(2,'0')}/${x.year}</td><td>${brl(x.amount)}</td><td>${x.note||'—'}</td><td><button class="danger-link" onclick="deletePayment(${x.id})">Excluir</button></td></tr>`)):'<p>Nenhum pagamento no filtro atual.</p>'}
function deletePayment(id){if(confirm('Excluir este pagamento?')){payments=payments.filter(x=>x.id!==id);localStorage.setItem(STORAGE.payments,JSON.stringify(payments));render()}}window.deletePayment=deletePayment;
function searchCaf(){let q=upper($('#cafSearch').value);if(!q)return $('#cafResult').innerHTML='';let d=data.filter(r=>upper(r.caf).includes(q));if(!d.length)return $('#cafResult').innerHTML='<p>Nenhuma CAF encontrada.</p>';let exact=d.filter(r=>upper(r.caf)===q);if(exact.length)d=exact;let fat=d.reduce((s,r)=>s+PRICES[r.tamanho],0);$('#cafResult').innerHTML=`<div class="cards"><article><label>CAF</label><strong>${d[0].caf}</strong><small>${d[0].cidade}/${d[0].uf}</small></article><article><label>AWBs</label><strong>${d.length}</strong></article><article><label>Faturamento</label><strong>${brl(fat)}</strong></article></div>`+table(['AWB','Tipo','Data','Peso','Categoria','Valor'],d.slice(0,500).map(r=>`<tr><td>${r.awb}</td><td>${r.tipo_item}</td><td>${r.data}</td><td>${r.peso}</td><td>${r.tamanho}</td><td>${brl(PRICES[r.tamanho])}</td></tr>`))}
function getField(o,...names){let map=Object.fromEntries(Object.keys(o).map(k=>[upper(k),k]));for(let n of names){let k=map[upper(n)];if(k!==undefined)return o[k]}return''}
function normalizeCAF(o){let awb=norm(getField(o,'awb1','awb')),peso=Number(String(getField(o,'peso')).replace(',','.'))||0;return{caf:norm(getField(o,'cafid1','caf')),data:parseDate(getField(o,'dt_finalizada_caf','dt_finalizada_caf_off','data')),data_abertura:parseDate(getField(o,'dt_abertura_caf')),entregues:Number(getField(o,'entregues'))||0,awb,peso,peso_cliente:Number(String(getField(o,'peso_cliente')).replace(',','.'))||0,tipo_item:identifyType(awb),tamanho:classify(awb,peso),valor_unitario:PRICES[classify(awb,peso)],motorista_id:norm(getField(o,'mot_id1')),motorista:norm(getField(o,'mot_nome1')),cnpj:norm(getField(o,'CNPJ')),razao_social:norm(getField(o,'motemp_razao_social')),placa:norm(getField(o,'vei_placa')),cidade:norm(getField(o,'cidade')),uf:norm(getField(o,'uf')),cliente:norm(getField(o,'nmfantasia')),tipo_produto:norm(getField(o,'ds_tipo_produto')),quinzena_original:norm(getField(o,'quinzena1')),modelo_pagamento:norm(getField(o,'ModeloPagamento'))}}
function sheetJson(ws,headerRow=1){return XLSX.utils.sheet_to_json(ws,{range:headerRow-1,defval:'',raw:true})}
function parseWorkbook(wb,file){let cafSheet=wb.Sheets['CAFS']||wb.Sheets['CAF_Consolidado'];if(!cafSheet)throw new Error('Aba CAFS não encontrada.');let raw=sheetJson(cafSheet,1),incoming=raw.map(normalizeCAF).filter(r=>r.awb&&r.caf);let required=['cafid1','awb1','peso','cidade'];let keys=raw[0]?Object.keys(raw[0]).map(upper):[];let missing=required.filter(k=>!keys.includes(upper(k)));if(missing.length)throw new Error('Colunas obrigatórias ausentes: '+missing.join(', '));let ap=[];if(wb.Sheets['APURACAO'])ap=sheetJson(wb.Sheets['APURACAO'],2);let official=ap.reduce((s,r)=>s+(Number(getField(r,'Total Pagar'))||0),0),calc=incoming.reduce((s,r)=>s+PRICES[r.tamanho],0);return{incoming,ap,official,calc,fileName:file.name}}
function handleFile(file){let reader=new FileReader();reader.onload=e=>{try{let wb=XLSX.read(e.target.result,{type:'array',cellDates:true}),p=parseWorkbook(wb,file),existing=new Set(data.map(r=>`${upper(r.caf)}|${upper(r.awb)}`)),fresh=p.incoming.filter(r=>!existing.has(`${upper(r.caf)}|${upper(r.awb)}`)),dups=p.incoming.length-fresh.length;pendingImport={...p,fresh,dups};$('#preview').innerHTML=`<div class="preview"><h3>${file.name}</h3><p><b>${num(p.incoming.length)}</b> registros • <b>${num(new Set(p.incoming.map(r=>r.caf)).size)}</b> CAFs • <b>${num(new Set(p.incoming.map(r=>r.cidade)).size)}</b> cidades</p><p>Calculado pelo sistema: <b>${brl(p.calc)}</b>${p.ap.length?` • Total APURACAO: <b>${brl(p.official)}</b> • Diferença: <b>${brl(p.calc-p.official)}</b>`:''}</p><p class="${dups?'warn':'ok'}">${num(dups)} duplicados ignorados • ${num(fresh.length)} novos</p><button id="confirmImport" ${fresh.length?'':'disabled'}>Confirmar importação</button></div>`;$('#confirmImport')?.addEventListener('click',confirmImport)}catch(err){toast(err.message||'Falha ao ler planilha.')}};reader.readAsArrayBuffer(file)}
function confirmImport(){if(!pendingImport)return;extra=dedupe([...extra,...pendingImport.fresh]);localStorage.setItem(STORAGE.extra,JSON.stringify(extra));data=dedupe([...base,...extra]);let p=pendingImport;imports.unshift({id:Date.now(),arquivo:p.fileName,registros:p.fresh.length,duplicados:p.dups,status:'Importado',calculado:p.calc,oficial:p.official,data:new Date().toISOString()});localStorage.setItem(STORAGE.imports,JSON.stringify(imports));pendingImport=null;try{populateFilters();render();renderHistory();}catch(err){console.error('W2 init error',err);toast('Falha ao iniciar dados: '+(err.message||err));}$('#preview').innerHTML='';toast('Importação concluída com sucesso.')}
function renderHistory(){let rows=imports.map(x=>`<tr><td>${x.data?new Date(x.data).toLocaleString('pt-BR'):'—'}</td><td>${x.arquivo}</td><td>${num(x.registros)}</td><td>${num(x.duplicados||0)}</td><td>${x.oficial?brl(x.oficial):'—'}</td><td>${x.status}</td></tr>`);$('#history').innerHTML=rows.length?table(['Data','Arquivo','Novos','Duplicados','Total oficial','Status'],rows):'<p>Nenhuma importação adicional nesta instalação.</p>'}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3200)}
function openTab(name){const page=$('#'+name);if(!page)return;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.page').forEach(x=>x.classList.toggle('active',x.id===name));if(name==='pagamentos')renderPayments();if(name==='importacoes')renderHistory()}
document.querySelector('nav').addEventListener('click',e=>{const b=e.target.closest('.tab');if(b)openTab(b.dataset.tab)});
$$('.filters select').forEach(x=>x.onchange=render);$('#clearFilters').onclick=()=>{$('#fAno').value='';$$('#monthMenu input[type=checkbox]').forEach(o=>o.checked=false);updateMonthLabel();$('#fQuinzena').value='';$('#fCidade').value='';$('#fTamanho').value='';render()};$('#cafSearch').oninput=searchCaf;$('#btnUpload').onclick=()=>{openTab('importacoes');$('#fileInput').click()};$('#drop').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>e.target.files[0]&&handleFile(e.target.files[0]);$('#drop').ondragover=e=>e.preventDefault();$('#drop').ondrop=e=>{e.preventDefault();e.dataTransfer.files[0]&&handleFile(e.dataTransfer.files[0])};

$('#monthToggle').onclick=e=>{e.stopPropagation();$('#monthMenu').classList.toggle('open');$('#monthToggle').classList.toggle('open')};
$('#monthMenu').onclick=e=>e.stopPropagation();
$('#monthMenu').onchange=e=>{if(e.target.matches('input[type=checkbox]')){updateMonthLabel();render()}};
document.addEventListener('click',e=>{if(e.target.closest('#monthAll')){$$('#monthMenu input[type=checkbox]').forEach(o=>o.checked=true);updateMonthLabel();render();return}if(e.target.closest('#monthNone')){$$('#monthMenu input[type=checkbox]').forEach(o=>o.checked=false);updateMonthLabel();render();return}if(!e.target.closest('#monthFilter')){$('#monthMenu').classList.remove('open');$('#monthToggle').classList.remove('open')}});
document.addEventListener('click',e=>{let b=e.target.closest('.pay-btn');if(b&&!b.disabled)return openPayment(b.dataset.city);if(e.target.closest('#closePaymentModal'))return closePaymentModal();if(e.target.closest('#savePayment'))return registerPayment();if(e.target.closest('#payFull'))return $('#mAmount').value=Number($('#mDebt').textContent.replace(/[^0-9,]/g,'').replace(',','.')).toFixed(2);if(e.target.closest('#paymentHistoryBtn')){let h=$('#paymentHistory');h.style.display=h.style.display==='none'?'block':'none';renderPaymentHistory()}});$('#paymentModal').onclick=e=>{if(e.target===$('#paymentModal'))closePaymentModal()};
try{populateFilters();render();renderHistory();}catch(err){console.error('W2 init error',err);toast('Falha ao iniciar dados: '+(err.message||err));}
