(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const MONTHS=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
  const SHORT=['JAN','FEV','MAR','ABR','MAIO','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];
  const received=[
    [2026,5,1,15169.50],[2026,5,2,50220.00],[2026,6,1,12951.00],[2026,6,2,11700.50],
    [2026,7,1,10570.00],[2026,7,2,20865.50],[2026,8,1,19785.00],[2026,8,2,29445.50]
  ];
  let ctx=null, rows=[], editing=null, loaded=false, manualReference=false, manualDescription=false;
  function reference(y,m,q){return `${q}Q${SHORT[m-1]||''}${String(y).slice(-2)}`}
  function description(y,m,q){return `Serviços de entrega de encomendas referentes à ${q}ª quinzena de ${MONTHS[m-1]||''} de ${y}.`}
  function parseMoney(value){let s=String(value||'').trim().replace(/R\$|\s/g,'');if(!s)return NaN;return Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s)}
  function period(r){return `${r.quinzena}ª quinzena de ${MONTHS[r.mes-1]} de ${r.ano}`}
  function info(message){$('nfStatus').textContent=message}
  function formRow(){return {ano:Number($('nfYear').value),mes:Number($('nfMonth').value),quinzena:Number($('nfHalf').value),referencia:$('nfReference').value.trim().toUpperCase(),codigo_contratante:$('nfClientCode').value.trim().toUpperCase(),valor_rem:parseMoney($('nfAmount').value),descricao:$('nfDescription').value.trim(),cte_existente:$('nfCte').value.trim(),observacao:$('nfNotes').value.trim()}}
  function validate(r){return r.ano>=2020&&r.ano<=2100&&r.mes>=1&&r.mes<=12&&[1,2].includes(r.quinzena)&&r.referencia&&r.descricao&&Number.isFinite(r.valor_rem)&&r.valor_rem>0}
  function updateSuggested(){const y=Number($('nfYear').value),m=Number($('nfMonth').value),q=Number($('nfHalf').value);if(!manualReference)$('nfReference').value=reference(y,m,q);if(!manualDescription)$('nfDescription').value=description(y,m,q);estimate()}
  function estimate(){if(!ctx)return;const y=Number($('nfYear').value),m=Number($('nfMonth').value),q=Number($('nfHalf').value);const matching=ctx.getData().filter(x=>{const d=ctx.dateParts(x.data);return d.year===y&&d.month===m&&d.quin===q});const total=matching.reduce((sum,x)=>sum+(ctx.PRICES[x.tamanho]||0),0);$('nfEstimate').textContent=`Cálculo por AWB importado: ${money(total)} (${matching.length} AWBs). O valor REM deve ser conferido no demonstrativo da Total Express.`}
  function reset(){editing=null;$('nfForm').reset();$('nfYear').value=new Date().getFullYear();$('nfMonth').value=new Date().getMonth()+1;$('nfHalf').value='1';$('nfClientCode').value='SE00041';$('nfSave').textContent='Salvar rascunho';manualReference=manualDescription=false;const s=ctx?.getSelectedPeriod();if(s?.year&&s.months?.length===1&&s.quin){$('nfYear').value=s.year;$('nfMonth').value=s.months[0];$('nfHalf').value=s.quin}updateSuggested()}
  function display(r){$('nfPvPeriod').textContent=period(r);$('nfPvReference').textContent=`${r.referencia||'—'} · ${r.codigo_contratante||'—'}`;$('nfPvDescription').textContent=r.descricao;$('nfPvAmount').textContent=money(r.valor_rem);$('nfPreview').showModal()}
  function button(label,action,className){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=className||'ghost';b.addEventListener('click',action);return b}
  function render(){const root=$('nfRecords');root.replaceChildren();if(!rows.length){const p=document.createElement('p');p.textContent='Nenhum rascunho salvo. Cadastre uma quinzena ou carregue os oito valores recebidos.';root.append(p);return}for(const r of [...rows].sort((a,b)=>b.ano-a.ano||b.mes-a.mes||b.quinzena-a.quinzena)){const item=document.createElement('article');item.className='nf-item';const left=document.createElement('div');const title=document.createElement('strong');title.textContent=`${r.referencia} · ${period(r)}`;const sub=document.createElement('small');sub.textContent=`${r.codigo_contratante||'Sem código do contratante'} · Rascunho, sem emissão`;left.append(title,sub);const right=document.createElement('div');right.className='nf-item-actions';const val=document.createElement('b');val.textContent=money(r.valor_rem);right.append(val,button('NFS de teste',()=>display(r)),button('Editar',()=>edit(r)),button('Excluir',()=>remove(r),'ghost nf-danger'));item.append(left,right);root.append(item)}}
  function edit(r){editing=r.id;$('nfYear').value=r.ano;$('nfMonth').value=r.mes;$('nfHalf').value=r.quinzena;$('nfAmount').value=Number(r.valor_rem).toFixed(2).replace('.',',');$('nfReference').value=r.referencia;$('nfClientCode').value=r.codigo_contratante||'';$('nfDescription').value=r.descricao;$('nfCte').value=r.cte_existente||'';$('nfNotes').value=r.observacao||'';manualReference=manualDescription=true;$('nfSave').textContent='Atualizar rascunho';estimate();document.getElementById('nfse').scrollIntoView({behavior:'smooth'})}
  async function remove(r){if(!confirm(`Excluir o rascunho ${r.referencia}?`))return;try{await W2DB.deleteNfseDraft(r.id);rows=rows.filter(x=>x.id!==r.id);render();if(editing===r.id)reset();info('Rascunho excluído.')}catch(e){info('Falha ao excluir: '+(e.message||e))}}
  async function refresh(){info('Carregando rascunhos…');try{rows=await W2DB.loadNfseDrafts();loaded=true;render();info(`${rows.length} rascunho(s) no Supabase.`)}catch(e){loaded=false;info('Não foi possível carregar os rascunhos. Execute supabase_schema_v2_5_nfse.sql no projeto Supabase e tente novamente. '+(e.message||e))}}
  async function save(ev){ev.preventDefault();const row=formRow();if(!validate(row)){info('Preencha ano, mês, quinzena, referência, valor REM positivo e descrição.');return}const btn=$('nfSave');btn.disabled=true;try{const saved=await W2DB.saveNfseDraft(editing?{...row,id:editing}:row);const idx=rows.findIndex(x=>x.id===saved.id);if(idx<0)rows.push(saved);else rows[idx]=saved;render();reset();info('Rascunho salvo no Supabase. Nenhuma NFS-e foi emitida.')}catch(e){info('Falha ao salvar: '+(e.message||e))}finally{btn.disabled=false}}
  async function loadEight(){if(!loaded){info('Carregue a lista antes de importar as quinzenas.');return}const missing=received.filter(([y,m,q])=>!rows.some(r=>r.ano===y&&r.mes===m&&r.quinzena===q&&r.tomador_cnpj==='73939449000193'));if(!missing.length){info('As oito quinzenas já constam como rascunho.');return}if(!confirm(`Carregar ${missing.length} quinzena(s) como rascunho? Nenhuma nota será emitida.`))return;const btn=$('nfLoadEight');btn.disabled=true;let saved=0;try{for(const [ano,mes,quinzena,valor_rem] of missing){const referencia=reference(ano,mes,quinzena);const row=await W2DB.saveNfseDraft({ano,mes,quinzena,valor_rem,referencia,codigo_contratante:'SE00041',descricao:description(ano,mes,quinzena),cte_existente:referencia==='2QMAIO26'?'499289':'',observacao:'Valor informado pela Total Express. Enquadramento fiscal pendente de validação.'});rows.push(row);saved++}render();info(`${saved} rascunho(s) incluído(s). Nenhuma NFS-e foi emitida.`)}catch(e){render();info(`${saved} salvo(s); falha na sequência: ${e.message||e}`)}finally{btn.disabled=false}}
  function init(context){ctx=context;$('nfMonth').innerHTML=MONTHS.map((m,i)=>`<option value="${i+1}">${m}</option>`).join('');$('nfForm').addEventListener('submit',save);$('nfReset').addEventListener('click',reset);$('nfTest').addEventListener('click',()=>{const r=formRow();if(!validate(r))return info('Preencha os dados da cobrança para visualizar o teste.');display(r)});$('nfLoadEight').addEventListener('click',loadEight);$('nfClose').addEventListener('click',()=>$('nfPreview').close());$('nfPrint').addEventListener('click',()=>window.print());$('nfReference').addEventListener('input',()=>manualReference=true);$('nfDescription').addEventListener('input',()=>manualDescription=true);['nfYear','nfMonth','nfHalf'].forEach(id=>$(id).addEventListener('change',updateSuggested));reset()}
  function show(){if(!ctx)return;const s=ctx.getSelectedPeriod();if(s.year&&s.months.length===1&&s.quin&&!editing){$('nfYear').value=s.year;$('nfMonth').value=s.months[0];$('nfHalf').value=s.quin;updateSuggested()}refresh()}
  window.W2NF={init,show};
})();
