-- W2 Sistema de Faturamento V2
create table if not exists public.importacoes (
  id bigint generated by default as identity primary key,
  email_message_id text unique,
  arquivo_nome text not null,
  arquivo_hash text,
  origem text not null default 'manual',
  recebido_em timestamptz,
  importado_em timestamptz not null default now(),
  registros_encontrados int not null default 0,
  registros_novos int not null default 0,
  duplicados int not null default 0,
  total_calculado numeric(14,2),
  total_oficial numeric(14,2),
  status text not null default 'importado',
  erro text
);

create table if not exists public.entregas (
  id bigint generated by default as identity primary key,
  importacao_id bigint references public.importacoes(id) on delete set null,
  caf_id text not null,
  awb text not null,
  data_abertura date,
  data_finalizacao date,
  peso numeric(12,3) not null default 0,
  peso_cliente numeric(12,3),
  tipo_item text not null check (tipo_item in ('CAIXA','CARTÃO')),
  categoria text not null check (categoria in ('CARTÃO','PEQUENO','MÉDIO','GRANDE')),
  valor_unitario numeric(12,2) not null,
  motorista_id text,
  motorista text,
  cidade text,
  uf text,
  placa text,
  cliente text,
  modelo_pagamento text,
  created_at timestamptz not null default now(),
  unique(caf_id, awb)
);

create table if not exists public.pagamentos_entregadores (
  id bigint generated by default as identity primary key,
  cidade text not null,
  entregador text not null,
  ano int not null,
  mes int not null check (mes between 1 and 12),
  quinzena int not null check (quinzena in (1,2)),
  valor numeric(12,2) not null check (valor > 0),
  data_pagamento date not null,
  observacao text,
  created_at timestamptz not null default now()
);

create index if not exists idx_entregas_data on public.entregas(data_finalizacao);
create index if not exists idx_entregas_cidade on public.entregas(cidade);
create index if not exists idx_pagamentos_periodo on public.pagamentos_entregadores(ano,mes,quinzena,cidade);
