-- W2 Dashboard CAF V2.0 - persistência no mesmo projeto Supabase do CheckLog
-- Execute uma única vez no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.dashboard_importacoes (
  id uuid primary key default gen_random_uuid(),
  arquivo text not null,
  registros_recebidos integer not null default 0,
  novos_registros integer not null default 0,
  duplicados integer not null default 0,
  status text not null default 'processando',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.dashboard_cafs (
  id bigint generated by default as identity primary key,
  caf text not null,
  awb text not null,
  data date,
  entregues integer not null default 0,
  peso numeric(14,4) not null default 0,
  tamanho text,
  cidade text,
  uf text,
  importacao_id uuid references public.dashboard_importacoes(id) on delete set null,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  constraint dashboard_cafs_caf_awb_key unique (caf, awb)
);

create table if not exists public.dashboard_pagamentos (
  id bigint generated by default as identity primary key,
  cidade text not null,
  entregador text not null,
  valor numeric(14,2) not null check (valor > 0),
  data_pagamento date not null,
  observacao text,
  ano integer not null,
  mes integer not null check (mes between 1 and 12),
  quinzena integer not null check (quinzena in (1,2)),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists idx_dashboard_cafs_data on public.dashboard_cafs(data);
create index if not exists idx_dashboard_cafs_cidade on public.dashboard_cafs(cidade);
create index if not exists idx_dashboard_cafs_caf on public.dashboard_cafs(caf);
create index if not exists idx_dashboard_importacoes_created_at on public.dashboard_importacoes(created_at desc);
create index if not exists idx_dashboard_pagamentos_periodo on public.dashboard_pagamentos(ano,mes,quinzena,cidade);

create or replace function public.dashboard_tem_acesso()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.perfis p
    where p.id = auth.uid()
      and coalesce(p.ativo,true) = true
      and p.acesso_dashboard = true
  );
$$;

grant execute on function public.dashboard_tem_acesso() to authenticated;

grant select, insert, update, delete on public.dashboard_cafs to authenticated;
grant select, insert, update, delete on public.dashboard_importacoes to authenticated;
grant select, insert, update, delete on public.dashboard_pagamentos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.dashboard_cafs enable row level security;
alter table public.dashboard_importacoes enable row level security;
alter table public.dashboard_pagamentos enable row level security;

drop policy if exists dashboard_cafs_acesso on public.dashboard_cafs;
create policy dashboard_cafs_acesso on public.dashboard_cafs for all to authenticated
using (public.dashboard_tem_acesso()) with check (public.dashboard_tem_acesso());

drop policy if exists dashboard_importacoes_acesso on public.dashboard_importacoes;
create policy dashboard_importacoes_acesso on public.dashboard_importacoes for all to authenticated
using (public.dashboard_tem_acesso()) with check (public.dashboard_tem_acesso());

drop policy if exists dashboard_pagamentos_acesso on public.dashboard_pagamentos;
create policy dashboard_pagamentos_acesso on public.dashboard_pagamentos for all to authenticated
using (public.dashboard_tem_acesso()) with check (public.dashboard_tem_acesso());
