-- W2 Sistema de Faturamento V2.1 - Supabase
create table if not exists public.importacoes (
  id bigint generated by default as identity primary key,
  email_message_id text unique,
  arquivo_nome text not null,
  arquivo_hash text,
  origem text not null default 'manual' check (origem in ('manual','outlook','migracao')),
  recebido_em timestamptz,
  importado_em timestamptz not null default now(),
  registros_encontrados int not null default 0,
  registros_novos int not null default 0,
  duplicados int not null default 0,
  total_calculado numeric(14,2),
  total_oficial numeric(14,2),
  status text not null default 'importado',
  erro text
);
create table if not exists public.entregas (
  id bigint generated by default as identity primary key,
  importacao_id bigint references public.importacoes(id) on delete set null,
  caf_id text not null,
  awb text not null,
  data_abertura date,
  data_finalizacao date,
  peso numeric(12,3) not null default 0,
  peso_cliente numeric(12,3),
  tipo_item text not null check (tipo_item in ('CAIXA','CARTÃO')),
  categoria text not null check (categoria in ('CARTÃO','PEQUENO','MÉDIO','GRANDE')),
  valor_unitario numeric(12,2) not null,
  motorista_id text,
  motorista text,
  cidade text,
  uf text,
  placa text,
  cliente text,
  modelo_pagamento text,
  created_at timestamptz not null default now(),
  unique(caf_id,awb)
);
create table if not exists public.fechamentos (
  id bigint generated by default as identity primary key,
  importacao_id bigint references public.importacoes(id) on delete set null,
  ano int not null,
  mes int not null check (mes between 1 and 12),
  quinzena int not null check (quinzena in (1,2)),
  total_calculado numeric(14,2),
  total_oficial numeric(14,2),
  diferenca numeric(14,2) generated always as (coalesce(total_oficial,0)-coalesce(total_calculado,0)) stored,
  created_at timestamptz not null default now(),
  unique(ano,mes,quinzena)
);
create table if not exists public.pagamentos_entregadores (
  id bigint generated by default as identity primary key,
  cidade text not null,
  entregador text not null,
  ano int not null,
  mes int not null check (mes between 1 and 12),
  quinzena int not null check (quinzena in (1,2)),
  valor numeric(12,2) not null check (valor > 0),
  data_pagamento date not null,
  observacao text,
  created_at timestamptz not null default now()
);
create index if not exists idx_entregas_data on public.entregas(data_finalizacao);
create index if not exists idx_entregas_cidade on public.entregas(cidade);
create index if not exists idx_pagamentos_periodo on public.pagamentos_entregadores(ano,mes,quinzena,cidade);

-- Segurança: nenhum dado operacional fica público pela anon key.
alter table public.importacoes enable row level security;
alter table public.entregas enable row level security;
alter table public.fechamentos enable row level security;
alter table public.pagamentos_entregadores enable row level security;

-- V2.1 prepara o banco para a autenticação da V2.2.
-- Usuários autenticados podem operar os dados; usuários anônimos não têm acesso.
drop policy if exists "w2_auth_importacoes" on public.importacoes;
create policy "w2_auth_importacoes" on public.importacoes for all to authenticated using (true) with check (true);
drop policy if exists "w2_auth_entregas" on public.entregas;
create policy "w2_auth_entregas" on public.entregas for all to authenticated using (true) with check (true);
drop policy if exists "w2_auth_fechamentos" on public.fechamentos;
create policy "w2_auth_fechamentos" on public.fechamentos for all to authenticated using (true) with check (true);
drop policy if exists "w2_auth_pagamentos" on public.pagamentos_entregadores;
create policy "w2_auth_pagamentos" on public.pagamentos_entregadores for all to authenticated using (true) with check (true);
