-- W2 Sistema de Faturamento V2.5: rascunhos de NFS-e.
-- Execute no SQL Editor do projeto Supabase do Faturamento, após V2.2.1.
-- Não emite nota nem altera os CT-es existentes.

create table if not exists public.nfse_rascunhos (
  id bigint generated by default as identity primary key,
  emitente_cnpj text not null default '46167015000140' check (emitente_cnpj = '46167015000140'),
  tomador_nome text not null default 'TEX COURIER S.A.',
  tomador_cnpj text not null default '73939449000193',
  ano integer not null check (ano between 2020 and 2100),
  mes integer not null check (mes between 1 and 12),
  quinzena integer not null check (quinzena in (1,2)),
  referencia text not null,
  codigo_contratante text,
  valor_rem numeric(14,2) not null check (valor_rem > 0),
  descricao text not null,
  cte_existente text,
  observacao text,
  status text not null default 'rascunho' check (status = 'rascunho'),
  criado_por uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tomador_cnpj, ano, mes, quinzena)
);

alter table public.nfse_rascunhos enable row level security;

drop policy if exists "nfse_financeiro_administrador_ler" on public.nfse_rascunhos;
create policy "nfse_financeiro_administrador_ler" on public.nfse_rascunhos
for select to authenticated using (exists (
  select 1 from public.perfis_faturamento p where p.id = auth.uid()
  and p.ativo = true and p.perfil in ('administrador','financeiro')
));

drop policy if exists "nfse_financeiro_administrador_inserir" on public.nfse_rascunhos;
create policy "nfse_financeiro_administrador_inserir" on public.nfse_rascunhos
for insert to authenticated with check (criado_por = auth.uid() and exists (
  select 1 from public.perfis_faturamento p where p.id = auth.uid()
  and p.ativo = true and p.perfil in ('administrador','financeiro')
));

drop policy if exists "nfse_financeiro_administrador_atualizar" on public.nfse_rascunhos;
create policy "nfse_financeiro_administrador_atualizar" on public.nfse_rascunhos
for update to authenticated using (exists (
  select 1 from public.perfis_faturamento p where p.id = auth.uid()
  and p.ativo = true and p.perfil in ('administrador','financeiro')
)) with check (exists (
  select 1 from public.perfis_faturamento p where p.id = auth.uid()
  and p.ativo = true and p.perfil in ('administrador','financeiro')
));

drop policy if exists "nfse_financeiro_administrador_excluir" on public.nfse_rascunhos;
create policy "nfse_financeiro_administrador_excluir" on public.nfse_rascunhos
for delete to authenticated using (exists (
  select 1 from public.perfis_faturamento p where p.id = auth.uid()
  and p.ativo = true and p.perfil in ('administrador','financeiro')
));
